/**
 * Tailwind Configuration File
 * ==========================================================================
 * Purpose:
 * Defines the design tokens (colors, typography, spacing) and build settings
 * for the Tailwind CSS framework used in this theme.
 *
 * Core Logic:
 * 1. Content Scanning: Tells Tailwind where to look for class names (PHP files).
 * 2. Importance Strategy: Sets `important: true` to override GP default styles.
 * 3. Theme Extension: Defines custom colors, fonts, and spacing values.
 *
 * Architecture Role:
 * This file is the "Brain" of the visual design system. It ensures that
 * utility classes generated by Tailwind match the project's design specs.
 *
 * 🚨 Critical Notes:
 * - Do NOT remove `important: true`. This is crucial for overriding GeneratePress.
 * - All custom colors must be defined in `theme.extend.colors` to avoid losing Tailwind defaults.
 * ==========================================================================
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  // 1. Content Scanning (扫描路径)
  // 告诉 Tailwind 在哪里寻找类名。包含所有可能出现 Tailwind 类的 PHP/JS/HTML 文件。
  content: [
    "./blocks/**/*.{php,html,js}",
    "./template-parts/**/*.php",
    "./templates/**/*.php",
    "./inc/**/*.php",
    "./functions.php",
    "./*.php",
  ],

  // 2. Importance Strategy (优先级策略)
  // 设置为 true，所有工具类都会添加 !important。
  // 目的：强制覆盖 GeneratePress 主题的默认样式，确保 Tailwind 布局生效。
  important: true,

  // 3. Theme Extension (主题扩展)
  theme: {
    extend: {
      // --- I. Color System (颜色系统) ---
      colors: {
        // 主色调 (Brand)
        primary: {
          DEFAULT: '#0047AB',
          hover: '#003A8C',
          active: '#002E6E',
        },
        // 语义化颜色
        industrial: '#1D2938', // 工业深色
        panel: '#F8F9FB',      // 面板背景
        heading: '#1D2938',    // 标题色
        body: '#667085',       // 正文色
        muted: '#98A2B3',      // 弱化文本
        inverse: '#FFFFFF',    // 反色文本
        
        // 背景色
        bg: {
          page: '#FFFFFF',
          section: '#F2F4F7',
          dark: '#1D2939',
        },
        // 边框色
        border: {
          DEFAULT: '#E4E7EC',
          strong: '#D0D5DD',
        },
      },

      // --- II. Typography (排版) ---
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'], // 用于技术参数
      },

      // --- III. Layout & Spacing (布局与间距) ---
      maxWidth: {
        // 安全的内容最大宽度，作用对象 : 具体的 内容区域 （文字、卡片、图片），背景是全宽的，但你的文字内容不能也铺满整个容器）
        container: '1280px', 
      },
      padding: {
        container: '24px',        // 容器内边距
        'section-y': '96px',      // 标准区块垂直间距
        'section-y-small': '64px', // 小区块垂直间距
        card: '32px',             // 卡片内边距
      },

      // --- IV. Border Radius (圆角) ---
      borderRadius: {
        card: '12px',   // 卡片圆角
        button: '8px',  // 按钮圆角
      },
    },
  },
  plugins: [],
};
