<?php

if ( function_exists( 'acf_add_local_field_group' ) ) {

    add_action( 'acf/init', function() {

        acf_add_local_field_group( array(
            'key' => 'group_page_home',
            'title' => 'Home Page (首页配置)',
            'fields' => array(
                array(
                    'key' => 'field_home_tab_overview',
                    'label' => 'Overview',
                    'type' => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key' => 'field_home_overview_hero_clone',
                    'label' => 'Hero Banner',
                    'name' => '',
                    'type' => 'clone',
                    'clone' => array(
                        'field_hero_title',
                        'field_hero_subtitle',
                        'field_hero_description',
                        'field_hero_buttons',
                        'field_hero_layout',
                        'field_hero_mobile_compact',
                        'field_hero_image',
                        'field_hero_mobile_image',
                        'field_hero_bg_color',
                        'field_hero_text_color',
                        'field_hero_btn_p_color',
                        'field_hero_btn_s_color',
                        'field_hero_show_stats',
                        'field_hero_stats',
                    ),
                    'display' => 'group',
                    'layout' => 'block',
                    'prefix_label' => 0,
                    'prefix_name' => 0,
                ),
                array(
                    'key' => 'field_home_tab_capability',
                    'label' => 'Capability',
                    'type' => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key' => 'field_home_capability_clone',
                    'label' => 'Capability List',
                    'name' => '',
                    'type' => 'clone',
                    'clone' => array(
                        'field_cl_section_title',
                        'field_cl_section_desc',
                        'field_cl_capabilities',
                        'field_cl_bg_color',
                        'field_cl_text_color',
                        'field_cl_accent_color',
                        'field_cl_anchor',
                    ),
                    'display' => 'group',
                    'layout' => 'block',
                    'prefix_label' => 0,
                    'prefix_name' => 0,
                ),
                array(
                    'key' => 'field_home_tab_review',
                    'label' => 'Review',
                    'type' => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key' => 'field_home_review_clone',
                    'label' => 'Review Grid',
                    'name' => '',
                    'type' => 'clone',
                    'clone' => array(
                        'field_title_main',
                        'field_title_highlight',
                        'field_reviews_subtitle',
                        'field_reviews_list',
                        'field_columns',
                        'field_spacing',
                        'field_card_style',
                        'field_mobile_compact',
                        'field_mobile_hide_content',
                        'field_block_id',
                        'field_custom_class',
                    ),
                    'display' => 'group',
                    'layout' => 'block',
                    'prefix_label' => 0,
                    'prefix_name' => 0,
                ),
                array(
                    'key' => 'field_home_tab_blog',
                    'label' => 'Blog',
                    'type' => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key' => 'field_home_blog_clone',
                    'label' => 'Related Blog',
                    'name' => '',
                    'type' => 'clone',
                    'clone' => array(
                        'field_66e3b0c0f0c8b1f',
                        'field_blog_title_highlight',
                        'field_66e3b0c0f0c8b29',
                        'field_66e3b0c0f0c8b33',
                        'field_66e3b0c0f0c8b3d',
                        'field_66e3b0c0f0c8b47',
                        'field_66e3b0c0f0c8b51',
                        'field_66e3b0c0f0c8b5b',
                        'field_66e3b0c0f0c8b65',
                        'field_66e3b0c0f0c8b79',
                        'field_66e3b0c0f0c8b83',
                        'field_related_blog_mobile_compact',
                        'field_related_blog_mobile_hide_subtitle',
                        'field_related_blog_block_id',
                        'field_related_blog_custom_class',
                    ),
                    'display' => 'group',
                    'layout' => 'block',
                    'prefix_label' => 0,
                    'prefix_name' => 0,
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'templates/page-home.php',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'seamless',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'active' => true,
        ) );
    } );
}
