<?php
/**
 * 角色：Material CPT 模块的字段 Schema 定义
 * 位置：/inc/acf/cpt/cpt-material.php
 * 说明：材料自定义post类型的字段逻辑
 */

if ( function_exists( 'acf_add_local_field_group' ) ) {

    add_action( 'acf/init', function() {
        acf_add_local_field_group( array(
            'key'   => 'group_cpt_material_fields',
            'title' => 'Material Fields',
            'fields' => array(
                array(
                    'key'       => 'field_mat_tab_overview',
                    'label'     => 'Overview',
                    'type'      => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key'          => 'field_mat_hero_clone_content',
                    'label'        => 'Hero Content',
                    'name'         => 'mat_hero_content',
                    'type'         => 'clone',
                    'clone'        => array(
                        'field_hero_title',
                        'field_hero_subtitle',
                        'field_hero_description',
                        'field_hero_buttons',
                    ),
                    'display'      => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name'  => 0,
                    'wrapper'      => array( 'width' => '100' ),
                ),
                array(
                    'key'          => 'field_mat_mfs_clone_content',
                    'label'        => 'Manufacturing Showcase Content',
                    'name'         => 'mat_mfs_content',
                    'type'         => 'clone',
                    'clone'        => array(
                        'field_mfs_title',
                        'field_mfs_subtitle',
                        'field_mfs_items',
                    ),
                    'display'      => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name'  => 0,
                    'wrapper'      => array( 'width' => '100' ),
                ),
                array(
                    'key'          => 'field_mat_hero_clone_design',
                    'label'        => 'Hero Design & Stats',
                    'name'         => 'mat_hero_design',
                    'type'         => 'clone',
                    'clone'        => array(
                        'field_hero_layout',
                        'field_hero_mobile_compact',
                        'field_hero_image',
                        'field_hero_mobile_image',
                        'field_hero_bg_color',
                        'field_hero_text_color',
                        'field_hero_btn_p_color',
                        'field_hero_btn_s_color',
                        'field_hero_show_stats',
                        'field_hero_stats',
                    ),
                    'display'      => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name'  => 0,
                    'wrapper'      => array( 'width' => '100' ),
                ),
                array(
                    'key'          => 'field_mat_mfs_clone_design',
                    'label'        => 'Manufacturing Showcase Design',
                    'name'         => 'mat_mfs_design',
                    'type'         => 'clone',
                    'clone'        => array(
                        'field_mfs_layout_mode',
                        'field_mfs_items_per_view',
                        'field_mfs_show_nav',
                        'field_mfs_mobile_compact',
                    ),
                    'display'      => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name'  => 0,
                    'wrapper'      => array( 'width' => '100' ),
                ),
                array(
                    'key'          => 'field_mat_mfs_clone_settings',
                    'label'        => 'Manufacturing Showcase Settings',
                    'name'         => 'mat_mfs_settings',
                    'type'         => 'clone',
                    'clone'        => array(
                        'field_mfs_anchor',
                        'field_mfs_css_class',
                    ),
                    'display'      => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name'  => 0,
                    'wrapper'      => array( 'width' => '100' ),
                ),

                array(
                    'key'       => 'field_mat_tab_tech',
                    'label'     => 'Technical Specs',
                    'type'      => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key'          => 'field_mat_ts_clone_content',
                    'label'        => 'Technical Specs Content',
                    'name'         => 'mat_ts_content',
                    'type'         => 'clone',
                    'clone'        => array(
                        'field_ts_material_label',
                        'field_ts_intro',
                        'field_ts_tabs',
                    ),
                    'display'      => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name'  => 0,
                    'wrapper'      => array( 'width' => '100' ),
                ),
                array(
                    'key'          => 'field_mat_mcap_clone_content',
                    'label'        => 'Manufacturing Capabilities Content',
                    'name'         => 'mat_mcap_content',
                    'type'         => 'clone',
                    'clone'        => array(
                        'field_mcap_section_title',
                        'field_mcap_intro',
                        'field_mcap_tabs',
                    ),
                    'display'      => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name'  => 0,
                    'wrapper'      => array( 'width' => '100' ),
                ),
                array(
                    'key'          => 'field_mat_ts_clone_design',
                    'label'        => 'Technical Specs Design',
                    'name'         => 'mat_ts_design',
                    'type'         => 'clone',
                    'clone'        => array(
                        'field_ts_table_mono',
                        'field_ts_mobile_hide_table',
                        'field_ts_table_scroll',
                    ),
                    'display'      => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name'  => 0,
                    'wrapper'      => array( 'width' => '100' ),
                ),
                array(
                    'key'          => 'field_mat_mcap_clone_design',
                    'label'        => 'Manufacturing Capabilities Design',
                    'name'         => 'mat_mcap_design',
                    'type'         => 'clone',
                    'clone'        => array(
                        'field_mcap_mobile_compact',
                        'field_mcap_use_mono_font',
                    ),
                    'display'      => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name'  => 0,
                    'wrapper'      => array( 'width' => '100' ),
                ),
                array(
                    'key'          => 'field_mat_ts_clone_settings',
                    'label'        => 'Technical Specs Settings',
                    'name'         => 'mat_ts_settings',
                    'type'         => 'clone',
                    'clone'        => array(
                        'field_ts_anchor',
                        'field_ts_css_class',
                    ),
                    'display'      => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name'  => 0,
                    'wrapper'      => array( 'width' => '100' ),
                ),
                array(
                    'key'          => 'field_mat_mcap_clone_settings',
                    'label'        => 'Manufacturing Capabilities Settings',
                    'name'         => 'mat_mcap_settings',
                    'type'         => 'clone',
                    'clone'        => array(
                        'field_mcap_anchor',
                        'field_mcap_css_class',
                    ),
                    'display'      => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name'  => 0,
                    'wrapper'      => array( 'width' => '100' ),
                ),

                array(
                    'key'       => 'field_mat_tab_blog',
                    'label'     => 'Blog',
                    'type'      => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key'          => 'field_mat_related_blog_clone_content',
                    'label'        => 'Related Blog Content',
                    'name'         => 'mat_related_blog_content',
                    'type'         => 'clone',
                    'clone'        => array(
                        'field_66e3b0c0f0c8b1f',
                        'field_blog_title_highlight',
                        'field_66e3b0c0f0c8b29',
                        'field_66e3b0c0f0c8b33',
                        'field_66e3b0c0f0c8b3d',
                        'field_66e3b0c0f0c8b47',
                        'field_66e3b0c0f0c8b51',
                        'field_66e3b0c0f0c8b5b',
                        'field_66e3b0c0f0c8b65',
                    ),
                    'display'      => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name'  => 0,
                    'wrapper'      => array( 'width' => '100' ),
                ),
                array(
                    'key'          => 'field_mat_related_blog_clone_design',
                    'label'        => 'Related Blog Design',
                    'name'         => 'mat_related_blog_design',
                    'type'         => 'clone',
                    'clone'        => array(
                        'field_66e3b0c0f0c8b79',
                        'field_66e3b0c0f0c8b83',
                        'field_related_blog_mobile_compact',
                        'field_related_blog_mobile_hide_subtitle',
                    ),
                    'display'      => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name'  => 0,
                    'wrapper'      => array( 'width' => '100' ),
                ),
                array(
                    'key'          => 'field_mat_related_blog_clone_settings',
                    'label'        => 'Related Blog Settings',
                    'name'         => 'mat_related_blog_settings',
                    'type'         => 'clone',
                    'clone'        => array(
                        'field_related_blog_block_id',
                        'field_related_blog_custom_class',
                    ),
                    'display'      => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name'  => 0,
                    'wrapper'      => array( 'width' => '100' ),
                ),

            ),
            'location' => array(
                array(
                    array(
                        'param'    => 'post_type',
                        'operator' => '==',
                        'value'    => 'material',
                    ),
                ),
            ),
            'menu_order'            => 0,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'active'                => true,
        ) );

    } );
}
