<?php
/**
 * 为 Capability CPT 增加页面布局管理字段
 * 用于控制 single-capability.php 页面的模块内容和配置
 */

if ( function_exists( 'acf_add_local_field_group' ) ) {


    add_action( 'acf/init', function() {
        acf_add_local_field_group( array(
            'key' => 'group_3dp_capability_page_layout',
            'title' => 'Capability Page Content (页面内容配置)',
            'fields' => array(
                array(
                    'key' => 'field_cap_tab_content',
                    'label' => 'Content',
                    'type' => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key' => 'field_cap_hero_clone_content',
                    'label' => 'Hero Content',
                    'name' => 'cap_hero_content',
                    'type' => 'clone',
                    'clone' => array(
                        'field_hero_title',
                        'field_hero_subtitle',
                        'field_hero_description',
                        'field_hero_buttons',
                    ),
                    'display' => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name' => 0,
                    'wrapper' => array('width' => '100'),
                ),
                array(
                    'key' => 'field_cap_hiw_clone_content',
                    'label' => 'Process Content',
                    'name' => 'cap_hiw_content',
                    'type' => 'clone',
                    'clone' => array(
                        'field_hiw_title',
                        'field_hiw_desc',
                        'field_hiw_steps',
                    ),
                    'display' => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name' => 0,
                    'wrapper' => array('width' => '100'),
                ),
                array(
                    'key' => 'field_cap_cdg_clone_content',
                    'label' => 'Design Guide Content',
                    'name' => 'cap_cdg_content',
                    'type' => 'clone',
                    'clone' => array(
                        'field_cdg_title',
                        'field_cdg_core_specs',
                        'field_cdg_tech_list',
                        'field_cdg_advice_group',
                    ),
                    'display' => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name' => 0,
                    'wrapper' => array('width' => '100'),
                ),
                array(
                    'key' => 'field_cap_ml_clone_content',
                    'label' => 'Material List Content',
                    'name' => 'cap_material_list_content',
                    'type' => 'clone',
                    'clone' => array(
                        'field_ml_process_list',
                    ),
                    'display' => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name' => 0,
                    'wrapper' => array('width' => '100'),
                ),
                array(
                    'key' => 'field_cap_ct_clone_content',
                    'label' => 'Comparison Table Content',
                    'name' => 'cap_comparison_content',
                    'type' => 'clone',
                    'clone' => array(
                        'field_ct_title',
                        'field_ct_header_group',
                        'field_ct_rows',
                    ),
                    'display' => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name' => 0,
                    'wrapper' => array('width' => '100'),
                ),
                array(
                    'key' => 'field_cap_tab_design',
                    'label' => 'Design',
                    'type' => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key' => 'field_cap_hero_clone_design',
                    'label' => 'Hero Design & Stats',
                    'name' => 'cap_hero_design',
                    'type' => 'clone',
                    'clone' => array(
                        'field_hero_layout',
                        'field_hero_mobile_compact',
                        'field_hero_image',
                        'field_hero_mobile_image',
                        'field_hero_bg_color',
                        'field_hero_text_color',
                        'field_hero_btn_p_color',
                        'field_hero_btn_s_color',
                        'field_hero_show_stats',
                        'field_hero_stats',
                    ),
                    'display' => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name' => 0,
                    'wrapper' => array('width' => '100'),
                ),
                array(
                    'key' => 'field_cap_hiw_clone_design',
                    'label' => 'Process Design',
                    'name' => 'cap_hiw_design',
                    'type' => 'clone',
                    'clone' => array(
                        'field_hiw_mb_hide_tip',
                        'field_hiw_mb_compact_mode',
                    ),
                    'display' => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name' => 0,
                    'wrapper' => array('width' => '100'),
                ),
                array(
                    'key' => 'field_cap_cdg_clone_design',
                    'label' => 'Design Guide Design',
                    'name' => 'cap_cdg_design',
                    'type' => 'clone',
                    'clone' => array(
                        'field_cdg_mb_mode',
                        'field_cdg_hide_advice_mb',
                    ),
                    'display' => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name' => 0,
                    'wrapper' => array('width' => '100'),
                ),
                array(
                    'key' => 'field_cap_ml_clone_design',
                    'label' => 'Material List Design',
                    'name' => 'cap_material_list_design',
                    'type' => 'clone',
                    'clone' => array(
                        'field_ml_mobile_layout',
                        'field_ml_display_mode',
                        'field_ml_mobile_hide_image',
                        'field_ml_bg_color',
                    ),
                    'display' => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name' => 0,
                    'wrapper' => array('width' => '100'),
                ),
                array(
                    'key' => 'field_cap_ct_clone_design',
                    'label' => 'Comparison Table Design',
                    'name' => 'cap_comparison_design',
                    'type' => 'clone',
                    'clone' => array(
                        'field_ct_highlight',
                        'field_ct_use_mono',
                        'field_ct_mobile_compact',
                    ),
                    'display' => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name' => 0,
                    'wrapper' => array('width' => '100'),
                ),
                array(
                    'key' => 'field_cap_tab_settings',
                    'label' => 'Settings',
                    'type' => 'tab',
                    'placement' => 'top',
                ),
                array(
                    'key' => 'field_cap_hiw_clone_settings',
                    'label' => 'Process Settings',
                    'name' => 'cap_hiw_settings',
                    'type' => 'clone',
                    'clone' => array(
                        'field_hiw_anchor',
                        'field_hiw_cta_label',
                        'field_hiw_cta_url',
                    ),
                    'display' => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name' => 0,
                    'wrapper' => array('width' => '100'),
                ),
                array(
                    'key' => 'field_cap_cdg_clone_settings',
                    'label' => 'Design Guide Settings',
                    'name' => 'cap_cdg_settings',
                    'type' => 'clone',
                    'clone' => array(
                        'field_cdg_anchor',
                    ),
                    'display' => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name' => 0,
                    'wrapper' => array('width' => '100'),
                ),
                array(
                    'key' => 'field_cap_ml_clone_settings',
                    'label' => 'Material List Settings',
                    'name' => 'cap_material_list_settings',
                    'type' => 'clone',
                    'clone' => array(
                        'field_ml_anchor_id',
                        'field_ml_custom_class',
                    ),
                    'display' => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name' => 0,
                    'wrapper' => array('width' => '100'),
                ),
                array(
                    'key' => 'field_cap_ct_clone_settings',
                    'label' => 'Comparison Table Settings',
                    'name' => 'cap_comparison_settings',
                    'type' => 'clone',
                    'clone' => array(
                        'field_ct_anchor',
                        'field_ct_custom_class',
                    ),
                    'display' => 'seamless',
                    'prefix_label' => 0,
                    'prefix_name' => 0,
                    'wrapper' => array('width' => '100'),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'capability',
                    ),
                ),
            ),
            'style' => 'seamless',
            'instruction_placement' => 'label',
        ) );
    });
}
