<?php
/**
 * Comparison Table Block 的ACF字段定义
 * 
 * 包含3D打印技术对比表格的标题、比较行和设计选项
 */

// 确保函数在ACF可用时才执行
if ( function_exists( 'acf_add_local_field_group' ) ) {
    // 注册Comparison Table Block的字段组
    function _3dp_comparison_table_fields() {
        acf_add_local_field_group( array(
            'key' => 'group_66e2a0c0f0c8b0c',
            'title' => 'Comparison Table Block',
            'fields' => array(
                // Content Tab
                array(
                    'key' => 'field_66e2a0c0f0c8b17',
                    'label' => 'Content',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_66e2a0c0f0c8b20',
                    'label' => 'Table Title',
                    'name' => 'table_title',
                    'type' => 'text',
                    'instructions' => '输入对比表格的标题（如 "MJF 3D printing service compared..."）',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 'MJF 3D printing service compared to other 3D printing technologies',
                    'placeholder' => '例如：MJF 3D printing service compared to other 3D printing technologies',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_66e2a0c0f0c8b2a',
                    'label' => 'Comparison Rows',
                    'name' => 'comparison_rows',
                    'type' => 'repeater',
                    'instructions' => '添加需要比较的技术行，每行包含技术名称和各项参数',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => 'field_66e2a0c0f0c8b34',
                    'min' => 1,
                    'max' => 10,
                    'layout' => 'table',
                    'button_label' => '添加技术行',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_66e2a0c0f0c8b34',
                            'label' => 'Tech Name',
                            'name' => 'tech_name',
                            'type' => 'text',
                            'instructions' => '输入技术名称（如 MJF, SLS, SLA...）',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '15',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '例如：MJF',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_66e2a0c0f0c8b3e',
                            'label' => 'Dimensional Accuracy',
                            'name' => 'accuracy',
                            'type' => 'text',
                            'instructions' => '输入尺寸精度（如 "± 0.3% with a lower limit of ± 0.3 mm"）',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '例如：± 0.3% with a lower limit of ± 0.3 mm',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_66e2a0c0f0c8b48',
                            'label' => 'Strengths',
                            'name' => 'strengths',
                            'type' => 'textarea',
                            'instructions' => '输入技术优势',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '例如：Design flexibility, support not required',
                            'maxlength' => '',
                            'rows' => 3,
                            'new_lines' => '',
                        ),
                        array(
                            'key' => 'field_66e2a0c0f0c8b52',
                            'label' => 'Build Volume',
                            'name' => 'build_volume',
                            'type' => 'text',
                            'instructions' => '输入成型体积（如 "380 x 285 x 380 mm"）',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '15',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '例如：380 x 285 x 380 mm',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_66e2a0c0f0c8b5c',
                            'label' => 'Layer Thickness',
                            'name' => 'layer_thickness',
                            'type' => 'text',
                            'instructions' => '输入层厚（如 "80µm"）',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '10',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '例如：80µm',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_66e2a0c0f0c8b66',
                            'label' => 'Min. Feature Size',
                            'name' => 'min_feature',
                            'type' => 'text',
                            'instructions' => '输入最小细节（如 "0.5 mm"）',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '15',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '例如：0.5 mm',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    ),
                ),
                // Design Tab
                array(
                    'key' => 'field_66e2a0c0f0c8b6f',
                    'label' => 'Design',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_66e2a0c0f0c8b79',
                    'label' => 'Highlight Row',
                    'name' => 'highlight_row',
                    'type' => 'select',
                    'instructions' => '选择需要高亮显示的技术行',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        '' => 'None',
                    ),
                    'default_value' => '',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 1,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                ),
                // Settings Tab
                array(
                    'key' => 'field_66e2a0c0f0c8b83',
                    'label' => 'Settings',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'block',
                        'operator' => '==',
                        'value' => 'acf/comparison-table',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        ) );
    }
    add_action( 'acf/init', '_3dp_comparison_table_fields' );
}
