<?php
/**
 * CTA Block 的ACF字段定义
 * 包含号召性用语模块的标题、描述、图片、按钮和设计选项
 * 位置：全局模块，很多页面都在用
 */

// 确保函数在ACF可用时才执行
if ( function_exists( 'acf_add_local_field_group' ) ) {
    // 注册CTA Block的字段组
    function _3dp_cta_fields() {
        acf_add_local_field_group( array(
            'key' => 'group_66e4c0c0f0c8b0b',
            'title' => 'CTA Block',
            'fields' => array(
                // Content Tab
                array(
                    'key' => 'field_66e4c0c0f0c8b16',
                    'label' => 'Content',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_66e4c0c0f0c8b1f',
                    'label' => 'CTA Title',
                    'name' => 'cta_title',
                    'type' => 'text',
                    'instructions' => '输入CTA模块的主标题（支持加粗或颜色高亮）',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 'You have the idea - we make it a reality',
                    'placeholder' => '例如：Start your 3D printing journey today',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_cta_title_highlight',
                    'label' => 'CTA Title Highlight',
                    'name' => 'cta_title_highlight',
                    'type' => 'text',
                    'instructions' => '标题中需要用品牌色高亮的部分，例如：a reality',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_66e4c0c0f0c8b29',
                    'label' => 'CTA Description',
                    'name' => 'cta_description',
                    'type' => 'textarea',
                    'instructions' => '输入CTA模块的详细描述文本（支持多行）',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 'We have partnered with CADmore to offer you easy and accessible design services. No matter if you are starting from scratch or need help with an existing project, CADmore can help you with any design request you may have.',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => 5,
                    'new_lines' => 'wpautop',
                ),
                array(
                    'key' => 'field_cta_highlight_metric',
                    'label' => 'Highlight Metric Text',
                    'name' => 'cta_highlight_metric',
                    'type' => 'text',
                    'instructions' => '描述文本中需要用等宽字体与主色突出显示的数值，例如：5 minutes',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_66e4c0c0f0c8b33',
                    'label' => 'CTA Image',
                    'name' => 'cta_image',
                    'type' => 'image',
                    'instructions' => '上传右侧特色图片（建议上传透明背景的PNG）',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => 'png,jpg,jpeg,webp',
                ),
                array(
                    'key' => 'field_66e4c0c0f0c8b3d',
                    'label' => 'CTA Button Group',
                    'name' => 'cta_button_group',
                    'type' => 'group',
                    'instructions' => '配置CTA按钮的文字、链接和图标',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_66e4c0c0f0c8b47',
                            'label' => 'Button Text',
                            'name' => 'button_text',
                            'type' => 'text',
                            'instructions' => '输入按钮文字',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'Start your design project here',
                            'placeholder' => '例如：Get Started',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_66e4c0c0f0c8b51',
                            'label' => 'Button Link',
                            'name' => 'button_link',
                            'type' => 'url',
                            'instructions' => '输入按钮链接',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_66e4c0c0f0c8b5b',
                            'label' => 'Button Icon',
                            'name' => 'button_icon',
                            'type' => 'select',
                            'instructions' => '选择要显示的按钮图标',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'none' => '无图标',
                                'arrow-right' => '向右箭头',
                                'external-link' => '外部链接',
                                'download' => '下载',
                                'envelope' => '邮件',
                                'phone' => '电话',
                            ),
                            'default_value' => 'none',
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_cta_secondary_button_group',
                    'label' => 'Secondary Button',
                    'name' => 'cta_secondary_button',
                    'type' => 'group',
                    'instructions' => '配置右侧次级按钮，例如：Contact Sales',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_cta_secondary_button_text',
                            'label' => 'Secondary Button Text',
                            'name' => 'text',
                            'type' => 'text',
                            'instructions' => '次级按钮文字，例如：Contact Sales',
                            'required' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'Contact Sales',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_cta_secondary_button_link',
                            'label' => 'Secondary Button Link',
                            'name' => 'url',
                            'type' => 'url',
                            'instructions' => '次级按钮链接地址，例如：/contact',
                            'required' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '/contact',
                            'placeholder' => '',
                        ),
                    ),
                ),
                // Design Tab
                array(
                    'key' => 'field_66e4c0c0f0c8b65',
                    'label' => 'Design',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_66e4c0c0f0c8b6f',
                    'label' => 'Layout Reverse',
                    'name' => 'layout_reverse',
                    'type' => 'true_false',
                    'instructions' => '是否左右对调布局（方便在不同页面交替使用）',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '左右对调布局',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
                array(
                    'key' => 'field_66e4c0c0f0c8b79',
                    'label' => 'Background Color',
                    'name' => 'bg_color',
                    'type' => 'color_picker',
                    'instructions' => '设置模块的背景颜色（默认浅灰或纯白）',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '#ffffff',
                    'enable_opacity' => 1,
                    'return_format' => 'rgba',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'block',
                        'operator' => '==',
                        'value' => 'acf/cta',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ));
    }
    add_action( 'acf/init', '_3dp_cta_fields' );
}
