<?php
/**
 * Feature Grid 区块的ACF字段定义
 * 位置: /inc/acf/field/feature-grid.php
 * 说明：这个模块已经不用了，主要是刚开始参考protolabs的所有工艺的模块做的，后续已经用其他模块替代
 */

// 确保函数在ACF可用时才执行
if ( function_exists( 'acf_add_local_field_group' ) ) {
    // 定义Feature Grid字段组
    acf_add_local_field_group( array(
        'key'                   => 'group_feature_grid',
        'title'                 => __( 'Feature Grid', '3d-printing' ),
        'fields'                => array(
            // Content 标签页
            array(
                'key'               => 'field_feature_grid_tab_content',
                'label'             => __( 'Content', '3d-printing' ),
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width'         => '',
                    'class'         => '',
                    'id'            => '',
                ),
                'placement'         => 'top',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_feature_grid_heading',
                'label'             => __( '模块大标题', '3d-printing' ),
                'name'              => 'grid_heading',
                'type'              => 'text',
                'instructions'      => __( 'Feature Grid模块的主标题', '3d-printing' ),
                'required'          => 1,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width'         => '',
                    'class'         => '',
                    'id'            => '',
                ),
                'default_value'     => __( '3D Printing Processes', '3d-printing' ),
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_feature_grid_subheading',
                'label'             => __( '模块描述文本', '3d-printing' ),
                'name'              => 'grid_subheading',
                'type'              => 'textarea',
                'instructions'      => __( 'Feature Grid模块的描述文字', '3d-printing' ),
                'required'          => 1,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width'         => '',
                    'class'         => '',
                    'id'            => '',
                ),
                'default_value'     => __( 'Our online 3D printing service enables you to 3D print your custom part on demand. We offer six 3D printing technologies to transform your 3D files into plastic, metal, and elastomeric parts.
With more than 120+ 3D printers, we have unmatched capacity that reliably delivers parts within days. In addition to a broad material selection, we offer several post-processing options to improve cosmetics or enhance mechanical properties.', '3d-printing' ),
                'placeholder'       => '',
                'maxlength'         => '',
                'rows'              => 5,
                'new_lines'         => 'wpautop',
            ),
            array(
                'key'               => 'field_feature_grid_items',
                'label'             => __( '功能卡片列表', '3d-printing' ),
                'name'              => 'grid_items',
                'type'              => 'repeater',
                'instructions'      => __( '展示3D打印工艺的功能卡片', '3d-printing' ),
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width'         => '',
                    'class'         => '',
                    'id'            => '',
                ),
                'collapsed'         => 'field_item_title',
                'min'               => 1,
                'max'               => 10,
                'layout'            => 'table',
                'button_label'      => __( '添加功能卡片', '3d-printing' ),
                'sub_fields'        => array(
                    array(
                        'key'               => 'field_item_title',
                        'label'             => __( '卡片标题', '3d-printing' ),
                        'name'              => 'item_title',
                        'type'              => 'text',
                        'instructions'      => __( '功能卡片的标题', '3d-printing' ),
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width'         => '',
                            'class'         => '',
                            'id'            => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => __( 'Metal 3D Printing', '3d-printing' ),
                        'prepend'           => '',
                        'append'            => '',
                        'maxlength'         => '',
                    ),
                    array(
                        'key'               => 'field_item_image',
                        'label'             => __( '卡片图片', '3d-printing' ),
                        'name'              => 'item_image',
                        'type'              => 'image',
                        'instructions'      => __( '功能卡片的图片', '3d-printing' ),
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width'         => '',
                            'class'         => '',
                            'id'            => '',
                        ),
                        'return_format'     => 'id',
                        'preview_size'      => 'medium',
                        'library'           => 'all',
                        'min_width'         => '',
                        'min_height'        => '',
                        'min_size'          => '',
                        'max_width'         => '',
                        'max_height'        => '',
                        'max_size'          => '',
                        'mime_types'        => '',
                    ),
                    array(
                        'key'               => 'field_item_description',
                        'label'             => __( '卡片简述', '3d-printing' ),
                        'name'              => 'item_description',
                        'type'              => 'textarea',
                        'instructions'      => __( '功能卡片的描述文字', '3d-printing' ),
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width'         => '',
                            'class'         => '',
                            'id'            => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => __( 'Direct metal laser sintering (DMLS) uses a fiber laser system that draws onto a surface of atomized metal powder, welding the powder into fully dense metal parts.', '3d-printing' ),
                        'maxlength'         => '',
                        'rows'              => 3,
                        'new_lines'         => 'wpautop',
                    ),
                    array(
                        'key'               => 'field_item_link',
                        'label'             => __( 'Learn More链接', '3d-printing' ),
                        'name'              => 'item_link',
                        'type'              => 'url',
                        'instructions'      => __( 'Learn More按钮的链接地址', '3d-printing' ),
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width'         => '',
                            'class'         => '',
                            'id'            => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                    ),
                ),
            ),
            // Design 标签页
            array(
                'key'               => 'field_feature_grid_tab_design',
                'label'             => __( 'Design', '3d-printing' ),
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width'         => '',
                    'class'         => '',
                    'id'            => '',
                ),
                'placement'         => 'top',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_feature_grid_columns_count',
                'label'             => __( '每行显示列数', '3d-printing' ),
                'name'              => 'columns_count',
                'type'              => 'select',
                'instructions'      => __( '选择每行显示的列数', '3d-printing' ),
                'required'          => 1,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width'         => '50',
                    'class'         => '',
                    'id'            => '',
                ),
                'choices'           => array(
                    '2' => __( '2列', '3d-printing' ),
                    '3' => __( '3列', '3d-printing' ),
                    '4' => __( '4列', '3d-printing' ),
                ),
                'default_value'     => '3',
                'allow_null'        => 0,
                'multiple'          => 0,
                'ui'                => 1,
                'return_format'     => 'value',
                'ajax'              => 0,
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_feature_grid_show_button',
                'label'             => __( '显示Learn More按钮', '3d-printing' ),
                'name'              => 'show_button',
                'type'              => 'true_false',
                'instructions'      => __( '是否在卡片底部显示Learn More按钮', '3d-printing' ),
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width'         => '50',
                    'class'         => '',
                    'id'            => '',
                ),
                'message'           => '',
                'default_value'     => 1,
                'ui'                => 1,
                'ui_on_text'        => '',
                'ui_off_text'       => '',
            ),
        ),
        'location'            => array(
            array(
                array(
                    'param'     => 'block',
                    'operator'  => '==',
                    'value'     => 'acf/feature-grid',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
    ) );
}