<?php
/**
 * ACF Fields 定义文件
 * 负责定义所有自定义的ACF字段组
 */

// 确保函数在ACF可用时才执行
if ( function_exists( 'acf_add_local_field_group' ) ) {
    // 定义Hero Banner字段组
    acf_add_local_field_group( array(
            'key'                   => 'group_hero_banner',
            'title'                 => __( 'Hero Banner', '3d-printing' ),
            'fields'                => array(
                // Content 标签页
                array(
                    'key'               => 'field_hero_tab_content',
                    'label'             => __( 'Content', '3d-printing' ),
                    'name'              => '',
                    'type'              => 'tab',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width'         => '',
                        'class'         => '',
                        'id'            => '',
                    ),
                    'placement'         => 'top',
                    'endpoint'          => 0,
                ),
                array(
                    'key'               => 'field_hero_title',
                    'label'             => __( '主标题', '3d-printing' ),
                    'name'              => 'hero_title',
                    'type'              => 'text',
                    'instructions'      => __( 'Hero Banner的主标题', '3d-printing' ),
                    'required'          => 1,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width'         => '',
                        'class'         => '',
                        'id'            => '',
                    ),
                    'default_value'     => __( 'Your Streamlined 3D Printing Service', '3d-printing' ),
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_hero_subtitle',
                    'label'             => __( '副标题', '3d-printing' ),
                    'name'              => 'hero_subtitle',
                    'type'              => 'text',
                    'instructions'      => __( 'Hero Banner的副标题', '3d-printing' ),
                    'required'          => 1,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width'         => '',
                        'class'         => '',
                        'id'            => '',
                    ),
                    'default_value'     => __( 'Get Quality Parts at the Best Price', '3d-printing' ),
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_hero_description',
                    'label'             => __( '描述文本', '3d-printing' ),
                    'name'              => 'hero_description',
                    'type'              => 'textarea',
                    'instructions'      => __( 'Hero Banner的描述文本', '3d-printing' ),
                    'required'          => 1,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width'         => '',
                        'class'         => '',
                        'id'            => '',
                    ),
                    'default_value'     => __( 'Compare manufacturers around the world in real time.
Order industrial-quality parts at the most competitive price.
We take care of everything, including your satisfaction.', '3d-printing' ),
                    'placeholder'       => '',
                    'maxlength'         => '',
                    'rows'              => 4,
                    'new_lines'         => 'wpautop',
                ),
                array(
                    'key'               => 'field_hero_buttons',
                    'label'             => __( '按钮组', '3d-printing' ),
                    'name'              => 'hero_buttons',
                    'type'              => 'repeater',
                    'instructions'      => __( 'Hero Banner的按钮组', '3d-printing' ),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width'         => '',
                        'class'         => '',
                        'id'            => '',
                    ),
                    'collapsed'         => 'field_button_text',
                    'min'               => 0,
                    'max'               => 2,
                    'layout'            => 'block',
                    'button_label'      => __( '添加按钮', '3d-printing' ),
                    'sub_fields'        => array(
                        array(
                            'key'               => 'field_button_text',
                            'label'             => __( '按钮文本', '3d-printing' ),
                            'name'              => 'button_text',
                            'type'              => 'text',
                            'instructions'      => '',
                            'required'          => 1,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width'         => '33',
                                'class'         => '',
                                'id'            => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                        ),
                        array(
                            'key'               => 'field_button_url',
                            'label'             => __( '按钮链接', '3d-printing' ),
                            'name'              => 'button_url',
                            'type'              => 'url',
                            'instructions'      => '',
                            'required'          => 1,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width'         => '50',
                                'class'         => '',
                                'id'            => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => 'https://',
                        ),
                        array(
                            'key'               => 'field_button_style',
                            'label'             => __( '按钮样式', '3d-printing' ),
                            'name'              => 'button_style',
                            'type'              => 'select',
                            'instructions'      => '',
                            'required'          => 1,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width'         => '17',
                                'class'         => '',
                                'id'            => '',
                            ),
                            'choices'           => array(
                                'primary'       => __( '主要', '3d-printing' ),
                                'secondary'     => __( '次要', '3d-printing' ),
                            ),
                            'default_value'     => 'primary',
                            'allow_null'        => 0,
                            'multiple'          => 0,
                            'ui'                => 0,
                            'return_format'     => 'value',
                            'ajax'              => 0,
                            'placeholder'       => '',
                        ),
                    ),
                ),
                array(
                    'key'               => 'field_hero_image',
                    'label'             => __( '右侧图片', '3d-printing' ),
                    'name'              => 'hero_image',
                    'type'              => 'image',
                    'instructions'      => __( 'Hero Banner右侧的图片', '3d-printing' ),
                    'required'          => 1,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width'         => '',
                        'class'         => '',
                        'id'            => '',
                    ),
                    'return_format'     => 'id',
                    'preview_size'      => 'medium',
                    'library'           => 'all',
                    'min_width'         => '',
                    'min_height'        => '',
                    'min_size'          => '',
                    'max_width'         => '',
                    'max_height'        => '',
                    'max_size'          => '',
                    'mime_types'        => '',
                ),
                
                // Design 标签页

                array(
                    'key'               => 'field_hero_tab_design',
                    'label'             => __( 'Design', '3d-printing' ),
                    'name'              => '',
                    'type'              => 'tab',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width'         => '',
                        'class'         => '',
                        'id'            => '',
                    ),
                    'placement'         => 'top',
                    'endpoint'          => 0,
                ),
                array(
                    'key'               => 'field_hero_layout',
                    'label'             => __( '布局样式', '3d-printing' ),
                    'name'              => 'hero_layout',
                    'type'              => 'select',
                    'instructions'      => __( '选择Hero Banner的布局样式', '3d-printing' ),
                    'required'          => 1,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width'         => '',
                        'class'         => '',
                        'id'            => '',
                    ),
                    'choices'           => array(
                        'split'         => __( '左文右图', '3d-printing' ),
                        'centered'      => __( '文字居中 + 背景大图', '3d-printing' ),
                    ),
                    'default_value'     => 'split',
                    'allow_null'        => 0,
                    'multiple'          => 0,
                    'ui'                => 1,
                    'return_format'     => 'value',
                    'ajax'              => 0,
                    'placeholder'       => '',
                ),
                array(
                    'key'               => 'field_hero_background_color',
                    'label'             => __( '背景颜色', '3d-printing' ),
                    'name'              => 'hero_background_color',
                    'type'              => 'color_picker',
                    'instructions'      => __( 'Hero Banner的背景颜色', '3d-printing' ),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width'         => '50',
                        'class'         => '',
                        'id'            => '',
                    ),
                    'default_value'     => '#ffffff',
                    'enable_opacity'    => 1,
                    'return_format'     => 'string',
                ),
                array(
                    'key'               => 'field_hero_text_color',
                    'label'             => __( '文本颜色', '3d-printing' ),
                    'name'              => 'hero_text_color',
                    'type'              => 'color_picker',
                    'instructions'      => __( 'Hero Banner的文本颜色', '3d-printing' ),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width'         => '50',
                        'class'         => '',
                        'id'            => '',
                    ),
                    'default_value'     => '#000000',
                    'enable_opacity'    => 1,
                    'return_format'     => 'string',
                ),
                array(
                    'key'               => 'field_hero_primary_button_color',
                    'label'             => __( '按钮主要颜色', '3d-printing' ),
                    'name'              => 'hero_primary_button_color',
                    'type'              => 'color_picker',
                    'instructions'      => __( '主要按钮的背景颜色', '3d-printing' ),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width'         => '50',
                        'class'         => '',
                        'id'            => '',
                    ),
                    'default_value'     => '#0073aa',
                    'enable_opacity'    => 1,
                    'return_format'     => 'string',
                ),
                array(
                    'key'               => 'field_hero_secondary_button_color',
                    'label'             => __( '按钮次要颜色', '3d-printing' ),
                    'name'              => 'hero_secondary_button_color',
                    'type'              => 'color_picker',
                    'instructions'      => __( '次要按钮的背景颜色', '3d-printing' ),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width'         => '50',
                        'class'         => '',
                        'id'            => '',
                    ),
                    'default_value'     => '#ffffff',
                    'enable_opacity'    => 1,
                    'return_format'     => 'string',
                ),
                
                // Settings 标签页
                array(
                    'key'               => 'field_hero_tab_settings',
                    'label'             => __( 'Settings', '3d-printing' ),
                    'name'              => '',
                    'type'              => 'tab',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width'         => '',
                        'class'         => '',
                        'id'            => '',
                    ),
                    'placement'         => 'top',
                    'endpoint'          => 0,
                ),
                array(
                    'key'               => 'field_hero_show_stats',
                    'label'             => __( '显示统计数据', '3d-printing' ),
                    'name'              => 'hero_show_stats',
                    'type'              => 'true_false',
                    'instructions'      => __( '是否显示底部统计数据', '3d-printing' ),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width'         => '',
                        'class'         => '',
                        'id'            => '',
                    ),
                    'message'           => __( '显示统计数据', '3d-printing' ),
                    'default_value'     => 1,
                    'ui'                => 1,
                    'ui_on_text'        => __( '是', '3d-printing' ),
                    'ui_off_text'       => __( '否', '3d-printing' ),
                ),
                array(
                    'key'               => 'field_hero_stats',
                    'label'             => __( '统计数据', '3d-printing' ),
                    'name'              => 'hero_stats',
                    'type'              => 'repeater',
                    'instructions'      => __( '底部显示的统计数据', '3d-printing' ),
                    'required'          => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field'     => 'field_hero_show_stats',
                                'operator'  => '==',
                                'value'     => '1',
                            ),
                        ),
                    ),
                    'wrapper'           => array(
                        'width'         => '',
                        'class'         => '',
                        'id'            => '',
                    ),
                    'collapsed'         => 'field_stat_number',
                    'min'               => 0,
                    'max'               => 5,
                    'layout'            => 'table',
                    'button_label'      => __( '添加统计数据', '3d-printing' ),
                    'sub_fields'        => array(
                        array(
                            'key'               => 'field_stat_number',
                            'label'             => __( '统计数字', '3d-printing' ),
                            'name'              => 'stat_number',
                            'type'              => 'text',
                            'instructions'      => '',
                            'required'          => 1,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width'         => '50',
                                'class'         => '',
                                'id'            => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                        ),
                        array(
                            'key'               => 'field_stat_description',
                            'label'             => __( '统计描述', '3d-printing' ),
                            'name'              => 'stat_description',
                            'type'              => 'text',
                            'instructions'      => '',
                            'required'          => 1,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width'         => '50',
                                'class'         => '',
                                'id'            => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                        ),
                    ),
                ),
            ),
            'location'            => array(
                array(
                    array(
                        'param'     => 'block',
                        'operator'  => '==',
                        'value'     => 'acf/hero-banner',
                    ),
                ),
            ),
            'menu_order'            => 0,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
        ) );
}