<?php
if ( function_exists( 'acf_add_local_field_group' ) ) {

    function _3dp_related_blog_fields() {
        acf_add_local_field_group( array(
            'key'                   => 'group_66e3b0c0f0c8b0b',
            'title'                 => 'Related Blog Block',
            'fields'                => array(
                array(
                    'key'       => 'field_66e3b0c0f0c8b16',
                    'label'     => 'Content',
                    'name'      => '',
                    'type'      => 'tab',
                    'placement' => 'top',
                    'endpoint'  => 0,
                ),
                array(
                    'key'           => 'field_66e3b0c0f0c8b1f',
                    'label'         => 'Blog Title',
                    'name'          => 'blog_title',
                    'type'          => 'text',
                    'instructions'  => '输入博客模块的大标题（如 "Latest Manufacturing"）',
                    'required'      => 1,
                    'wrapper'       => array(
                        'width' => '66',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value' => 'Latest Manufacturing',
                    'placeholder'   => '例如：Latest Manufacturing',
                ),
                array(
                    'key'           => 'field_blog_title_highlight',
                    'label'         => 'Blog Title Highlight',
                    'name'          => 'blog_title_highlight',
                    'type'          => 'text',
                    'instructions'  => '用于高亮显示的标题部分（如 "Insights"）',
                    'required'      => 0,
                    'wrapper'       => array(
                        'width' => '34',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value' => 'Insights',
                    'placeholder'   => '例如：Insights',
                ),
                array(
                    'key'           => 'field_66e3b0c0f0c8b29',
                    'label'         => 'Blog Subtitle',
                    'name'          => 'blog_subtitle',
                    'type'          => 'text',
                    'instructions'  => '输入博客模块的副标题',
                    'required'      => 0,
                    'wrapper'       => array(
                        'width' => '100',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value' => '',
                    'placeholder'   => '例如：获取全球制造网络的最新技术指南、行业案例等',
                ),
                array(
                    'key'           => 'field_66e3b0c0f0c8b33',
                    'label'         => 'Posts Mode',
                    'name'          => 'posts_mode',
                    'type'          => 'select',
                    'instructions'  => '选择博客文章的抓取模式',
                    'required'      => 1,
                    'wrapper'       => array(
                        'width' => '100',
                        'class' => '',
                        'id'    => '',
                    ),
                    'choices'       => array(
                        'latest'   => '最新发布',
                        'category' => '指定分类',
                        'manual'   => '手动挑选',
                    ),
                    'default_value' => 'latest',
                    'allow_null'    => 0,
                    'multiple'      => 0,
                    'ui'            => 0,
                    'return_format' => 'value',
                    'ajax'          => 0,
                    'placeholder'   => '',
                ),
                array(
                    'key'               => 'field_66e3b0c0f0c8b3d',
                    'label'             => 'Select Category',
                    'name'              => 'select_category',
                    'type'              => 'taxonomy',
                    'instructions'      => '选择要展示的博客分类',
                    'required'          => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field'    => 'field_66e3b0c0f0c8b33',
                                'operator' => '==',
                                'value'    => 'category',
                            ),
                        ),
                    ),
                    'wrapper'           => array(
                        'width' => '100',
                        'class' => '',
                        'id'    => '',
                    ),
                    'taxonomy'          => 'category',
                    'field_type'        => 'select',
                    'allow_null'        => 1,
                    'add_term'          => 0,
                    'save_terms'        => 0,
                    'load_terms'        => 0,
                    'return_format'     => 'id',
                    'multiple'          => 0,
                ),
                array(
                    'key'               => 'field_66e3b0c0f0c8b47',
                    'label'             => 'Manual Posts',
                    'name'              => 'manual_posts',
                    'type'              => 'relationship',
                    'instructions'      => '手动选择要展示的博客文章',
                    'required'          => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field'    => 'field_66e3b0c0f0c8b33',
                                'operator' => '==',
                                'value'    => 'manual',
                            ),
                        ),
                    ),
                    'wrapper'           => array(
                        'width' => '100',
                        'class' => '',
                        'id'    => '',
                    ),
                    'post_type'         => array( 'post' ),
                    'taxonomy'          => '',
                    'filters'           => array( 'search', 'post_type', 'taxonomy' ),
                    'elements'          => '',
                    'min'               => 1,
                    'max'               => 6,
                    'return_format'     => 'id',
                ),
                array(
                    'key'           => 'field_66e3b0c0f0c8b51',
                    'label'         => 'Posts Count',
                    'name'          => 'posts_count',
                    'type'          => 'number',
                    'instructions'  => '设置要显示的文章数量（latest/category 模式有效）',
                    'required'      => 1,
                    'wrapper'       => array(
                        'width' => '50',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value' => 3,
                    'min'           => 1,
                    'max'           => 6,
                    'step'          => 1,
                ),
                array(
                    'key'           => 'field_66e3b0c0f0c8b5b',
                    'label'         => 'Button Text',
                    'name'          => 'button_text',
                    'type'          => 'text',
                    'instructions'  => '输入 "View All" 按钮的文字',
                    'required'      => 0,
                    'wrapper'       => array(
                        'width' => '50',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value' => 'View All Blogs',
                    'placeholder'   => '例如：View All Blogs',
                ),
                array(
                    'key'           => 'field_66e3b0c0f0c8b65',
                    'label'         => 'Button Link',
                    'name'          => 'button_link',
                    'type'          => 'url',
                    'instructions'  => '输入 "View All" 按钮的跳转链接',
                    'required'      => 0,
                    'wrapper'       => array(
                        'width' => '100',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value' => '/blog',
                    'placeholder'   => '',
                ),
                array(
                    'key'       => 'field_related_blog_design_tab',
                    'label'     => 'Design',
                    'name'      => '',
                    'type'      => 'tab',
                    'placement' => 'top',
                    'endpoint'  => 0,
                ),
                array(
                    'key'           => 'field_66e3b0c0f0c8b79',
                    'label'         => 'Posts Per Row',
                    'name'          => 'posts_per_row',
                    'type'          => 'select',
                    'instructions'  => '选择桌面端每行显示的文章数量',
                    'required'      => 1,
                    'wrapper'       => array(
                        'width' => '50',
                        'class' => '',
                        'id'    => '',
                    ),
                    'choices'       => array(
                        '3' => '3列',
                        '4' => '4列',
                    ),
                    'default_value' => '3',
                    'allow_null'    => 0,
                    'multiple'      => 0,
                    'ui'            => 0,
                    'return_format' => 'value',
                    'ajax'          => 0,
                    'placeholder'   => '',
                ),
                array(
                    'key'           => 'field_66e3b0c0f0c8b83',
                    'label'         => 'Show Excerpt',
                    'name'          => 'show_excerpt',
                    'type'          => 'true_false',
                    'instructions'  => '是否显示文章摘要',
                    'required'      => 0,
                    'wrapper'       => array(
                        'width' => '50',
                        'class' => '',
                        'id'    => '',
                    ),
                    'message'       => '显示文章摘要',
                    'default_value' => 1,
                    'ui'            => 0,
                ),
                array(
                    'key'           => 'field_related_blog_mobile_compact',
                    'label'         => 'Mobile Compact Mode',
                    'name'          => 'mobile_compact_mode',
                    'type'          => 'true_false',
                    'instructions'  => '在手机端使用更紧凑的卡片间距与排版',
                    'required'      => 0,
                    'wrapper'       => array(
                        'width' => '50',
                        'class' => '',
                        'id'    => '',
                    ),
                    'message'       => '启用移动端紧凑模式',
                    'default_value' => 1,
                    'ui'            => 0,
                ),
                array(
                    'key'           => 'field_related_blog_mobile_hide_subtitle',
                    'label'         => 'Mobile Hide Subtitle',
                    'name'          => 'mobile_hide_subtitle',
                    'type'          => 'true_false',
                    'instructions'  => '在手机端隐藏模块副标题文案',
                    'required'      => 0,
                    'wrapper'       => array(
                        'width' => '50',
                        'class' => '',
                        'id'    => '',
                    ),
                    'message'       => '移动端隐藏副标题',
                    'default_value' => 0,
                    'ui'            => 0,
                ),
                array(
                    'key'       => 'field_related_blog_settings_tab',
                    'label'     => 'Settings',
                    'name'      => '',
                    'type'      => 'tab',
                    'placement' => 'top',
                    'endpoint'  => 0,
                ),
                array(
                    'key'           => 'field_related_blog_block_id',
                    'label'         => 'Block ID',
                    'name'          => 'related_blog_block_id',
                    'type'          => 'text',
                    'instructions'  => '为该模块添加自定义ID（用于锚点链接或CSS定位）',
                    'required'      => 0,
                    'wrapper'       => array(
                        'width' => '50',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value' => '',
                    'placeholder'   => '例如：latest-insights',
                ),
                array(
                    'key'           => 'field_related_blog_custom_class',
                    'label'         => 'Custom Class',
                    'name'          => 'related_blog_custom_class',
                    'type'          => 'text',
                    'instructions'  => '为该模块添加自定义CSS类名',
                    'required'      => 0,
                    'wrapper'       => array(
                        'width' => '50',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value' => '',
                    'placeholder'   => '例如：section-latest-blog',
                ),
            ),
            'location'              => array(
                array(
                    array(
                        'param'    => 'block',
                        'operator' => '==',
                        'value'    => 'acf/related-blog',
                    ),
                ),
            ),
            'menu_order'            => 0,
            'position'              => 'normal',
            'style'                 => 'seamless',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
            'show_in_rest'          => 0,
        ) );
    }
    add_action( 'acf/init', '_3dp_related_blog_fields' );
}
