<?php
/**
 * Related Blog Block 的ACF字段定义
 * 
 * 包含博客文章展示模块的标题、数据抓取逻辑和视觉控制
 */

// 确保函数在ACF可用时才执行
if ( function_exists( 'acf_add_local_field_group' ) ) {
    // 注册Related Blog Block的字段组
    function _3dp_related_blog_fields() {
        acf_add_local_field_group( array(
            'key' => 'group_66e3b0c0f0c8b0b',
            'title' => 'Related Blog Block',
            'fields' => array(
                // Content Tab
                array(
                    'key' => 'field_66e3b0c0f0c8b16',
                    'label' => 'Content',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_66e3b0c0f0c8b1f',
                    'label' => 'Blog Title',
                    'name' => 'blog_title',
                    'type' => 'text',
                    'instructions' => '输入博客模块的大标题（如 "Blog and Article"）',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 'Blog and Article',
                    'placeholder' => '例如：Blog and Article',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_66e3b0c0f0c8b29',
                    'label' => 'Blog Subtitle',
                    'name' => 'blog_subtitle',
                    'type' => 'text',
                    'instructions' => '输入博客模块的副标题',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_66e3b0c0f0c8b33',
                    'label' => 'Posts Mode',
                    'name' => 'posts_mode',
                    'type' => 'select',
                    'instructions' => '选择博客文章的抓取模式',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'latest' => '最新发布',
                        'category' => '指定分类',
                        'manual' => '手动挑选',
                    ),
                    'default_value' => 'latest',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_66e3b0c0f0c8b3d',
                    'label' => 'Select Category',
                    'name' => 'select_category',
                    'type' => 'taxonomy',
                    'instructions' => '选择要展示的博客分类',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_66e3b0c0f0c8b33',
                                'operator' => '==',
                                'value' => 'category',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'taxonomy' => 'category',
                    'field_type' => 'select',
                    'allow_null' => 1,
                    'add_term' => 0,
                    'save_terms' => 0,
                    'load_terms' => 0,
                    'return_format' => 'id',
                    'multiple' => 0,
                ),
                array(
                    'key' => 'field_66e3b0c0f0c8b47',
                    'label' => 'Manual Posts',
                    'name' => 'manual_posts',
                    'type' => 'relationship',
                    'instructions' => '手动选择要展示的博客文章',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_66e3b0c0f0c8b33',
                                'operator' => '==',
                                'value' => 'manual',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'post',
                    ),
                    'taxonomy' => '',
                    'filters' => array(
                        0 => 'search',
                        1 => 'post_type',
                        2 => 'taxonomy',
                    ),
                    'elements' => '',
                    'min' => 1,
                    'max' => 6,
                    'return_format' => 'id',
                ),
                array(
                    'key' => 'field_66e3b0c0f0c8b51',
                    'label' => 'Posts Count',
                    'name' => 'posts_count',
                    'type' => 'number',
                    'instructions' => '设置要显示的文章数量',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 3,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => 1,
                    'max' => 6,
                    'step' => 1,
                ),
                array(
                    'key' => 'field_66e3b0c0f0c8b5b',
                    'label' => 'Button Text',
                    'name' => 'button_text',
                    'type' => 'text',
                    'instructions' => '输入"View All"按钮的文字',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 'View All Blogs',
                    'placeholder' => '例如：View All Blogs',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_66e3b0c0f0c8b65',
                    'label' => 'Button Link',
                    'name' => 'button_link',
                    'type' => 'url',
                    'instructions' => '输入"View All"按钮的跳转链接',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '/blog',
                    'placeholder' => '',
                ),
                // Design Tab
                array(
                    'key' => 'field_66e3b0c0f0c8b6f',
                    'label' => 'Design',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_66e3b0c0f0c8b79',
                    'label' => 'Posts Per Row',
                    'name' => 'posts_per_row',
                    'type' => 'select',
                    'instructions' => '选择每行显示的文章数量',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        '3' => '3列',
                        '4' => '4列',
                    ),
                    'default_value' => '3',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_66e3b0c0f0c8b83',
                    'label' => 'Show Excerpt',
                    'name' => 'show_excerpt',
                    'type' => 'true_false',
                    'instructions' => '是否显示文章摘要',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '显示文章摘要',
                    'default_value' => 1,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'block',
                        'operator' => '==',
                        'value' => 'acf/related-blog',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ));
    }
    add_action( 'acf/init', '_3dp_related_blog_fields' );
}