<?php
/**
 * Review Grid Block 的ACF字段定义
 * 
 * 包含客户评价网格的标题和评价列表
 */

// 确保函数在ACF可用时才执行
if ( function_exists( 'acf_add_local_field_group' ) ) {
    // 注册Review Grid Block的字段组
    function _3dp_review_grid_fields() {
        acf_add_local_field_group( array(
            'key' => 'group_66e2a0c0f0c8b0b',
            'title' => 'Review Grid Block',
            'fields' => array(
                // Content Tab
                array(
                    'key' => 'field_66e2a0c0f0c8b16',
                    'label' => 'Content',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_66e2a0c0f0c8b1f',
                    'label' => 'Reviews Title',
                    'name' => 'reviews_title',
                    'type' => 'text',
                    'instructions' => '输入评价模块的大标题（如 "What our customers say"）',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 'What our customers say',
                    'placeholder' => '例如：What our customers say',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_66e2a0c0f0c8b29',
                    'label' => 'Reviews List',
                    'name' => 'reviews_list',
                    'type' => 'repeater',
                    'instructions' => '添加客户评价列表，每个评价包含用户头像、姓名、职位和评价内容',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => 'field_66e2a0c0f0c8b33',
                    'min' => 1,
                    'max' => 12,
                    'layout' => 'block',
                    'button_label' => '添加评价',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_66e2a0c0f0c8b33',
                            'label' => 'User Name',
                            'name' => 'user_name',
                            'type' => 'text',
                            'instructions' => '输入用户姓名',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '例如：Khalid Bou-Rabee',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_66e2a0c0f0c8b3d',
                            'label' => 'User Title',
                            'name' => 'user_title',
                            'type' => 'text',
                            'instructions' => '输入用户的职位或公司名',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '例如：Founder, Harambe System',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_66e2a0c0f0c8b47',
                            'label' => 'User Photo',
                            'name' => 'user_photo',
                            'type' => 'image',
                            'instructions' => '上传用户头像图片',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '30',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => 'jpg,jpeg,png,webp',
                        ),
                        array(
                            'key' => 'field_66e2a0c0f0c8b51',
                            'label' => 'Review Text',
                            'name' => 'review_text',
                            'type' => 'textarea',
                            'instructions' => '输入客户评价内容',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '例如："Craftcloud has been a joy to work with..."',
                            'maxlength' => '',
                            'rows' => 6,
                            'new_lines' => 'wpautop',
                        ),
                    ),
                ),
                // Design Tab
                array(
                    'key' => 'field_66e2a0c0f0c8b5b',
                    'label' => 'Design',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_66e2a0c0f0c8b65',
                    'label' => 'Columns Count',
                    'name' => 'review_columns_count',
                    'type' => 'select',
                    'instructions' => '选择每行显示几个评价卡片',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        '2' => '2列',
                        '3' => '3列',
                        '4' => '4列',
                    ),
                    'default_value' => '3',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_66e2a0c0f0c8b6f',
                    'label' => 'Spacing',
                    'name' => 'review_spacing',
                    'type' => 'select',
                    'instructions' => '选择评价卡片之间的间距大小',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'small' => '小',
                        'medium' => '中',
                        'large' => '大',
                    ),
                    'default_value' => 'medium',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_66e2a0c0f0c8b79',
                    'label' => 'Card Style',
                    'name' => 'review_card_style',
                    'type' => 'select',
                    'instructions' => '选择评价卡片的样式',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'default' => '默认样式',
                        'shadow' => '带阴影',
                        'bordered' => '带边框',
                    ),
                    'default_value' => 'default',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                ),
                // Settings Tab
                array(
                    'key' => 'field_66e2a0c0f0c8b83',
                    'label' => 'Settings',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_66e2a0c0f0c8b8d',
                    'label' => 'Block ID',
                    'name' => 'review_grid_block_id',
                    'type' => 'text',
                    'instructions' => '为该模块添加自定义ID（用于锚点链接或CSS定位）',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '例如：reviews-section',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_66e2a0c0f0c8b97',
                    'label' => 'Custom Class',
                    'name' => 'review_grid_custom_class',
                    'type' => 'text',
                    'instructions' => '为该模块添加自定义CSS类名',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '例如：custom-review-grid',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'block',
                        'operator' => '==',
                        'value' => 'acf/review-grid',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ));
    }
    add_action( 'acf/init', '_3dp_review_grid_fields' );
}