<?php
if ( function_exists( 'acf_add_local_field_group' ) ) {
    function _3dp_review_grid_fields() {
        acf_add_local_field_group( array(
            'key'                   => 'group_66e2a0c0f0c8b0b',
            'title'                 => 'Review Grid Block',
            'fields'                => array(
                array(
                    'key'       => 'field_content_tab',
                    'label'     => 'Content',
                    'name'      => '',
                    'type'      => 'tab',
                    'placement' => 'top',
                    'endpoint'  => 0,
                ),
                array(
                    'key'           => 'field_title_main',
                    'label'         => 'Title Main',
                    'name'          => 'title_main',
                    'type'          => 'text',
                    'required'      => 1,
                    'wrapper'       => array( 'width' => '66' ),
                    'default_value' => 'Global Partner',
                    'placeholder'   => '例如：Global Partner',
                ),
                array(
                    'key'           => 'field_title_highlight',
                    'label'         => 'Title Highlight',
                    'name'          => 'title_highlight',
                    'type'          => 'text',
                    'required'      => 1,
                    'wrapper'       => array( 'width' => '34' ),
                    'default_value' => 'Trust',
                    'placeholder'   => '例如：Trust',
                ),
                array(
                    'key'         => 'field_reviews_subtitle',
                    'label'       => 'Short Description',
                    'name'        => 'reviews_subtitle',
                    'type'        => 'textarea',
                    'required'    => 0,
                    'wrapper'     => array( 'width' => '100' ),
                    'rows'        => 3,
                    'new_lines'   => 'wpautop',
                    'placeholder' => '例如：在 95 个国家/地区...',
                ),
                array(
                    'key'           => 'field_reviews_list',
                    'label'         => 'Reviews List',
                    'name'          => 'reviews_list',
                    'type'          => 'repeater',
                    'required'      => 1,
                    'wrapper'       => array( 'width' => '100' ),
                    'collapsed'     => 'field_user_name',
                    'min'           => 1,
                    'max'           => 12,
                    'layout'        => 'block',
                    'button_label'  => '添加评价',
                    'sub_fields'    => array(
                        array(
                            'key'           => 'field_user_photo',
                            'label'         => 'User Photo',
                            'name'          => 'user_photo',
                            'type'          => 'image',
                            'required'      => 1,
                            'wrapper'       => array( 'width' => '33' ),
                            'return_format' => 'array',
                            'preview_size'  => 'thumbnail',
                            'library'       => 'all',
                            'mime_types'    => 'jpg,jpeg,png,webp',
                        ),
                        array(
                            'key'         => 'field_user_name',
                            'label'       => 'User Name',
                            'name'        => 'user_name',
                            'type'        => 'text',
                            'required'    => 1,
                            'wrapper'     => array( 'width' => '33' ),
                            'placeholder' => '例如：Marcus Chen',
                        ),
                        array(
                            'key'         => 'field_user_title',
                            'label'       => 'User Title',
                            'name'        => 'user_title',
                            'type'        => 'text',
                            'required'    => 1,
                            'wrapper'     => array( 'width' => '34' ),
                            'placeholder' => '例如：CTO, AeroSpace Dynamic',
                        ),
                        array(
                            'key'           => 'field_stars_count',
                            'label'         => 'Stars',
                            'name'          => 'stars_count',
                            'type'          => 'select',
                            'required'      => 1,
                            'wrapper'       => array( 'width' => '33' ),
                            'choices'       => array( '1' => '1', '2' => '2', '3' => '3', '4' => '4', '5' => '5' ),
                            'default_value' => '5',
                            'return_format' => 'value',
                        ),
                        array(
                            'key'           => 'field_verified',
                            'label'         => 'Verified',
                            'name'          => 'verified',
                            'type'          => 'true_false',
                            'required'      => 0,
                            'wrapper'       => array( 'width' => '33' ),
                            'message'       => '标记为已验证',
                            'default_value' => 1,
                        ),
                        array(
                            'key'         => 'field_review_text',
                            'label'       => 'Review Text',
                            'name'        => 'review_text',
                            'type'        => 'textarea',
                            'required'    => 1,
                            'wrapper'     => array( 'width' => '100' ),
                            'rows'        => 6,
                            'new_lines'   => 'wpautop',
                            'placeholder' => '例如："PROTO_FAB 交付..."',
                        ),
                    ),
                ),
                array(
                    'key'       => 'field_design_tab',
                    'label'     => 'Design',
                    'name'      => '',
                    'type'      => 'tab',
                    'placement' => 'top',
                    'endpoint'  => 0,
                ),
                array(
                    'key'           => 'field_columns',
                    'label'         => 'Columns Count',
                    'name'          => 'review_columns_count',
                    'type'          => 'select',
                    'wrapper'       => array( 'width' => '50' ),
                    'choices'       => array( '1' => '1列', '2' => '2列', '3' => '3列', '4' => '4列' ),
                    'default_value' => '3',
                    'return_format' => 'value',
                ),
                array(
                    'key'           => 'field_spacing',
                    'label'         => 'Spacing',
                    'name'          => 'review_spacing',
                    'type'          => 'select',
                    'wrapper'       => array( 'width' => '50' ),
                    'choices'       => array( 'small' => '小', 'medium' => '中', 'large' => '大' ),
                    'default_value' => 'medium',
                    'return_format' => 'value',
                ),
                array(
                    'key'           => 'field_card_style',
                    'label'         => 'Card Style',
                    'name'          => 'review_card_style',
                    'type'          => 'select',
                    'wrapper'       => array( 'width' => '100' ),
                    'choices'       => array( 'default' => '默认样式', 'shadow' => '带阴影', 'bordered' => '带边框' ),
                    'default_value' => 'default',
                    'return_format' => 'value',
                ),
                array(
                    'key'           => 'field_mobile_compact',
                    'label'         => 'Mobile Compact Mode',
                    'name'          => 'mobile_compact_mode',
                    'type'          => 'true_false',
                    'wrapper'       => array( 'width' => '50' ),
                    'message'       => '启用移动端紧凑模式',
                    'default_value' => 1,
                ),
                array(
                    'key'           => 'field_mobile_hide_content',
                    'label'         => 'Mobile Hide Content',
                    'name'          => 'mobile_hide_content',
                    'type'          => 'true_false',
                    'wrapper'       => array( 'width' => '50' ),
                    'message'       => '在移动端隐藏描述',
                    'default_value' => 0,
                ),
                array(
                    'key'       => 'field_settings_tab',
                    'label'     => 'Settings',
                    'name'      => '',
                    'type'      => 'tab',
                    'placement' => 'top',
                    'endpoint'  => 0,
                ),
                array(
                    'key'         => 'field_block_id',
                    'label'       => 'Block ID',
                    'name'        => 'review_grid_block_id',
                    'type'        => 'text',
                    'wrapper'     => array( 'width' => '50' ),
                    'placeholder' => '例如：reviews-section',
                ),
                array(
                    'key'         => 'field_custom_class',
                    'label'       => 'Custom Class',
                    'name'        => 'review_grid_custom_class',
                    'type'        => 'text',
                    'wrapper'     => array( 'width' => '50' ),
                    'placeholder' => '例如：custom-review-grid',
                ),
            ),
            'location'              => array(
                array(
                    array(
                        'param'    => 'block',
                        'operator' => '==',
                        'value'    => 'acf/review-grid',
                    ),
                ),
            ),
            'menu_order'            => 0,
            'position'              => 'normal',
            'style'                 => 'seamless',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
            'show_in_rest'          => 0,
        ) );
    }
    add_action( 'acf/init', '_3dp_review_grid_fields' );
}
