<?php
/**
 * 角色：Trusted By (受信任的客户)
 * 备注：在材料页展示受信任的客户logo，通常是服务企业的logo
 * 目前是全局模块，用于首页的
 */
if ( function_exists( 'acf_add_local_field_group' ) ) {
	add_action( 'acf/init', function() {
		acf_add_local_field_group( array(
			'key'                   => 'group_trusted_by',
			'title'                 => __( 'Trusted By', '3d-printing' ),
			'fields'                => array(
				array(
					'key'               => 'field_trusted_by_tab_content',
					'label'             => __( 'Content', '3d-printing' ),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width'         => '',
						'class'         => '',
						'id'            => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_trusted_by_title',
					'label'             => __( '标题文本', '3d-printing' ),
					'name'              => 'trusted_by_title',
					'type'              => 'text',
					'instructions'      => __( 'Trusted By区块的标题文本', '3d-printing' ),
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width'         => '50',
						'class'         => '',
						'id'            => '',
					),
					'default_value'     => __( 'Trusted by Global Industry Leaders', '3d-printing' ),
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_trusted_by_description',
					'label'             => __( '描述文本', '3d-printing' ),
					'name'              => 'trusted_by_description',
					'type'              => 'textarea',
					'instructions'      => __( '辅助描述文案，例如展示服务企业数量和覆盖国家。', '3d-printing' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width'         => '50',
						'class'         => '',
						'id'            => '',
					),
					'default_value'     => __( 'We empower 140,000+ engineering teams across 95 countries with precision-grade manufacturing.', '3d-printing' ),
					'placeholder'       => '',
					'maxlength'         => '',
					'rows'              => 2,
					'new_lines'         => 'br',
				),
				array(
					'key'               => 'field_trusted_by_logos',
					'label'             => __( '合作伙伴Logo', '3d-printing' ),
					'name'              => 'trusted_by_logos',
					'type'              => 'repeater',
					'instructions'      => __( '展示的合作伙伴或客户Logo（建议：横向Logo，透明背景）', '3d-printing' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width'         => '',
						'class'         => '',
						'id'            => '',
					),
					'collapsed'         => 'field_logo_label',
					'min'               => 0,
					'max'               => 10,
					'layout'            => 'block',
					'button_label'      => __( '添加Logo', '3d-printing' ),
					'sub_fields'        => array(
						array(
							'key'               => 'field_logo_image',
							'label'             => __( 'Logo图片', '3d-printing' ),
							'name'              => 'logo_image',
							'type'              => 'image',
							'instructions'      => __( '建议：横向Logo，透明背景，约240x40px，格式优先SVG，其次PNG。', '3d-printing' ),
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width'         => '33',
								'class'         => '',
								'id'            => '',
							),
							'return_format'     => 'id',
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
						array(
							'key'               => 'field_logo_label',
							'label'             => __( 'Logo名称', '3d-printing' ),
							'name'              => 'logo_label',
							'type'              => 'text',
							'instructions'      => __( '后台识别用名称，例如：Amazon、Google 等。', '3d-printing' ),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width'         => '33',
								'class'         => '',
								'id'            => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_logo_alt_text',
							'label'             => __( '替代文本', '3d-printing' ),
							'name'              => 'logo_alt_text',
							'type'              => 'text',
							'instructions'      => __( 'Logo的替代文本（提高可访问性，不填写时可在渲染时回退为Logo名称）。', '3d-printing' ),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width'         => '34',
								'class'         => '',
								'id'            => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
				array(
					'key'               => 'field_trusted_by_tab_design',
					'label'             => __( 'Design', '3d-printing' ),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width'         => '',
						'class'         => '',
						'id'            => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_trusted_by_background_color',
					'label'             => __( '背景颜色', '3d-printing' ),
					'name'              => 'trusted_by_background_color',
					'type'              => 'color_picker',
					'instructions'      => __( 'Trusted By区块的背景颜色', '3d-printing' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width'         => '50',
						'class'         => '',
						'id'            => '',
					),
					'default_value'     => '#ffffff',
					'enable_opacity'    => 1,
					'return_format'     => 'string',
				),
				array(
					'key'               => 'field_trusted_by_title_color',
					'label'             => __( '标题颜色', '3d-printing' ),
					'name'              => 'trusted_by_title_color',
					'type'              => 'color_picker',
					'instructions'      => __( '标题文本的颜色', '3d-printing' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width'         => '50',
						'class'         => '',
						'id'            => '',
					),
					'default_value'     => '#000000',
					'enable_opacity'    => 1,
					'return_format'     => 'string',
				),
				array(
					'key'               => 'field_trusted_by_tab_settings',
					'label'             => __( 'Settings', '3d-printing' ),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width'         => '',
						'class'         => '',
						'id'            => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_trusted_by_enable_animation',
					'label'             => __( '启用滚动动画', '3d-printing' ),
					'name'              => 'trusted_by_enable_animation',
					'type'              => 'true_false',
					'instructions'      => __( '是否启用无限横向滚动的Logo云效果。', '3d-printing' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width'         => '33',
						'class'         => '',
						'id'            => '',
					),
					'ui'                => 1,
					'default_value'     => 1,
				),
				array(
					'key'               => 'field_trusted_by_animation_speed',
					'label'             => __( '滚动速度', '3d-printing' ),
					'name'              => 'trusted_by_animation_speed',
					'type'              => 'select',
					'instructions'      => __( '控制Logo云的滚动速度。', '3d-printing' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width'         => '33',
						'class'         => '',
						'id'            => '',
					),
					'choices'           => array(
						'slow'   => __( 'Slow', '3d-printing' ),
						'normal' => __( 'Normal', '3d-printing' ),
						'fast'   => __( 'Fast', '3d-printing' ),
					),
					'default_value'     => 'normal',
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'placeholder'       => '',
					'return_format'     => 'value',
				),
				array(
					'key'               => 'field_trusted_by_pause_on_hover',
					'label'             => __( '鼠标悬停暂停', '3d-printing' ),
					'name'              => 'trusted_by_pause_on_hover',
					'type'              => 'true_false',
					'instructions'      => __( '鼠标悬停在Logo云上时是否暂停滚动。', '3d-printing' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width'         => '34',
						'class'         => '',
						'id'            => '',
					),
					'ui'                => 1,
					'default_value'     => 1,
				),
			),
			'location'            => array(
				array(
					array(
						'param'     => 'block',
						'operator'  => '==',
						'value'     => 'acf/trusted-by',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'seamless',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		) );
	} );
}
