<?php
/**
 * Trusted By 区块的ACF字段定义
 * 位置: /inc/acf/field/trusted-by.php
 */

// 确保函数在ACF可用时才执行
if ( function_exists( 'acf_add_local_field_group' ) ) {
    // 定义Trusted By字段组
    acf_add_local_field_group( array(
        'key'                   => 'group_trusted_by',
        'title'                 => __( 'Trusted By', '3d-printing' ),
        'fields'                => array(
            // Content 标签页
            array(
                'key'               => 'field_trusted_by_tab_content',
                'label'             => __( 'Content', '3d-printing' ),
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width'         => '',
                    'class'         => '',
                    'id'            => '',
                ),
                'placement'         => 'top',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_trusted_by_title',
                'label'             => __( '标题文本', '3d-printing' ),
                'name'              => 'trusted_by_title',
                'type'              => 'text',
                'instructions'      => __( 'Trusted By区块的标题文本', '3d-printing' ),
                'required'          => 1,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width'         => '',
                    'class'         => '',
                    'id'            => '',
                ),
                'default_value'     => __( 'Access 1,000,000+ fuel, charging, and service points across Europe!', '3d-printing' ),
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_trusted_by_logos',
                'label'             => __( '合作伙伴Logo', '3d-printing' ),
                'name'              => 'trusted_by_logos',
                'type'              => 'repeater',
                'instructions'      => __( '展示的合作伙伴或客户Logo', '3d-printing' ),
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width'         => '',
                    'class'         => '',
                    'id'            => '',
                ),
                'collapsed'         => 'field_logo_image',
                'min'               => 0,
                'max'               => 10,
                'layout'            => 'table',
                'button_label'      => __( '添加Logo', '3d-printing' ),
                'sub_fields'        => array(
                    array(
                        'key'               => 'field_logo_image',
                        'label'             => __( 'Logo图片', '3d-printing' ),
                        'name'              => 'logo_image',
                        'type'              => 'image',
                        'instructions'      => __( '合作伙伴的Logo图片', '3d-printing' ),
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width'         => '',
                            'class'         => '',
                            'id'            => '',
                        ),
                        'return_format'     => 'id',
                        'preview_size'      => 'medium',
                        'library'           => 'all',
                        'min_width'         => '',
                        'min_height'        => '',
                        'min_size'          => '',
                        'max_width'         => '',
                        'max_height'        => '',
                        'max_size'          => '',
                        'mime_types'        => '',
                    ),
                    array(
                        'key'               => 'field_logo_alt_text',
                        'label'             => __( '替代文本', '3d-printing' ),
                        'name'              => 'logo_alt_text',
                        'type'              => 'text',
                        'instructions'      => __( 'Logo的替代文本（提高可访问性）', '3d-printing' ),
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width'         => '',
                            'class'         => '',
                            'id'            => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                        'maxlength'         => '',
                    ),
                ),
            ),
            // Design 标签页
            array(
                'key'               => 'field_trusted_by_tab_design',
                'label'             => __( 'Design', '3d-printing' ),
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width'         => '',
                    'class'         => '',
                    'id'            => '',
                ),
                'placement'         => 'top',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_trusted_by_background_color',
                'label'             => __( '背景颜色', '3d-printing' ),
                'name'              => 'trusted_by_background_color',
                'type'              => 'color_picker',
                'instructions'      => __( 'Trusted By区块的背景颜色', '3d-printing' ),
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width'         => '50',
                    'class'         => '',
                    'id'            => '',
                ),
                'default_value'     => '#ffffff',
                'enable_opacity'    => 1,
                'return_format'     => 'string',
            ),
            array(
                'key'               => 'field_trusted_by_title_color',
                'label'             => __( '标题颜色', '3d-printing' ),
                'name'              => 'trusted_by_title_color',
                'type'              => 'color_picker',
                'instructions'      => __( '标题文本的颜色', '3d-printing' ),
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width'         => '50',
                    'class'         => '',
                    'id'            => '',
                ),
                'default_value'     => '#000000',
                'enable_opacity'    => 1,
                'return_format'     => 'string',
            ),
        ),
        'location'            => array(
            array(
                array(
                    'param'     => 'block',
                    'operator'  => '==',
                    'value'     => 'acf/trusted-by',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
    ) );
}
