<?php
/**
 * Why Choose Us Block 的ACF字段定义
 * 
 * 包含左侧图片和右侧多个理由项
 */

// 确保函数在ACF可用时才执行
if ( function_exists( 'acf_add_local_field_group' ) ) {
    // 注册Why Choose Us Block的字段组
    function _3dp_why_choose_us_fields() {
        acf_add_local_field_group( array(
            'key' => 'group_66e1c0f0c8b0b',
            'title' => 'Why Choose Us Block',
            'fields' => array(
                // Content Tab
                array(
                    'key' => 'field_66e1c0f0c8b16',
                    'label' => 'Content',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_66e1c0f0c8b1f',
                    'label' => 'Left Image',
                    'name' => 'why_choose_us_left_image',
                    'type' => 'image',
                    'instructions' => '上传Why Choose Us模块左侧的图片',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => 'jpg,jpeg,png,webp',
                ),
                array(
                    'key' => 'field_66e1c0f0c8b29',
                    'label' => 'Reasons',
                    'name' => 'why_choose_us_reasons',
                    'type' => 'repeater',
                    'instructions' => '添加选择我们的理由列表，每个理由包含标题和描述',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => 'field_66e1c0f0c8b33',
                    'min' => 1,
                    'max' => 8,
                    'layout' => 'block',
                    'button_label' => '添加理由',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_66e1c0f0c8b33',
                            'label' => 'Reason Title',
                            'name' => 'reason_title',
                            'type' => 'text',
                            'instructions' => '输入理由的标题',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '例如：高精度打印',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_66e1c0f0c8b3d',
                            'label' => 'Reason Description',
                            'name' => 'reason_description',
                            'type' => 'textarea',
                            'instructions' => '输入理由的详细描述',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '例如：我们使用顶级设备，确保打印精度达到±0.01mm',
                            'maxlength' => '',
                            'rows' => 4,
                            'new_lines' => 'br',
                        ),
                    ),
                ),
                // Design Tab
                array(
                    'key' => 'field_66e1c0f0c8b47',
                    'label' => 'Design',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_66e1c0f0c8b51',
                    'label' => 'Layout Style',
                    'name' => 'why_choose_us_layout_style',
                    'type' => 'select',
                    'instructions' => '选择模块的布局风格',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'image-left' => '图片在左，文字在右',
                        'image-right' => '图片在右，文字在左',
                    ),
                    'default_value' => 'image-left',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_66e1c0f0c8b5b',
                    'label' => 'Spacing',
                    'name' => 'why_choose_us_spacing',
                    'type' => 'select',
                    'instructions' => '选择模块的内边距大小',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'small' => '小',
                        'medium' => '中',
                        'large' => '大',
                    ),
                    'default_value' => 'medium',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                ),
                // Settings Tab
                array(
                    'key' => 'field_66e1c0f0c8b65',
                    'label' => 'Settings',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_66e1c0f0c8b6f',
                    'label' => 'Block ID',
                    'name' => 'why_choose_us_block_id',
                    'type' => 'text',
                    'instructions' => '为该模块添加自定义ID（用于锚点链接或CSS定位）',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '例如：why-choose-us-section',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_66e1c0f0c8b79',
                    'label' => 'Custom Class',
                    'name' => 'why_choose_us_custom_class',
                    'type' => 'text',
                    'instructions' => '为该模块添加自定义CSS类名',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '例如：custom-why-choose-us',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'block',
                        'operator' => '==',
                        'value' => 'acf/why-choose-us',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ));
    }
    add_action( 'acf/init', '_3dp_why_choose_us_fields' );
}